/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.estadisticas;

/**
 *
 * @author franc
 */
public class estadisticasIndex extends javax.swing.JFrame {

    /**
     * Creates new form estadisticasIndex
     */
    public estadisticasIndex() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BienvenidoLbl4 = new javax.swing.JLabel();
        BienvenidoLbl3 = new javax.swing.JLabel();
        BienvenidoLbl = new javax.swing.JLabel();
        BienvenidoLbl2 = new javax.swing.JLabel();
        BienvenidoLbl1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPuntajes = new javax.swing.JTable();
        regresarBtn = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        puntajeTxt = new javax.swing.JTextField();
        nicknameTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BienvenidoLbl4.setBackground(new java.awt.Color(87, 198, 196));
        BienvenidoLbl4.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        BienvenidoLbl4.setForeground(new java.awt.Color(255, 255, 255));
        BienvenidoLbl4.setText("Puntaje global");
        jPanel1.add(BienvenidoLbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 70, -1, -1));

        BienvenidoLbl3.setBackground(new java.awt.Color(87, 198, 196));
        BienvenidoLbl3.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        BienvenidoLbl3.setForeground(new java.awt.Color(255, 255, 255));
        BienvenidoLbl3.setText("Tu puntaje es..");
        jPanel1.add(BienvenidoLbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, -1, -1));

        BienvenidoLbl.setBackground(new java.awt.Color(87, 198, 196));
        BienvenidoLbl.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        BienvenidoLbl.setForeground(new java.awt.Color(255, 255, 255));
        BienvenidoLbl.setText("estadisticas");
        jPanel1.add(BienvenidoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        BienvenidoLbl2.setBackground(new java.awt.Color(87, 198, 196));
        BienvenidoLbl2.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        BienvenidoLbl2.setForeground(new java.awt.Color(255, 255, 255));
        BienvenidoLbl2.setText("a la seccion");
        jPanel1.add(BienvenidoLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        BienvenidoLbl1.setBackground(new java.awt.Color(87, 198, 196));
        BienvenidoLbl1.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        BienvenidoLbl1.setForeground(new java.awt.Color(255, 255, 255));
        BienvenidoLbl1.setText("Bienvenido");
        jPanel1.add(BienvenidoLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel2.setBackground(new java.awt.Color(87, 198, 196));
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 600));

        tablaPuntajes.setBackground(new java.awt.Color(87, 198, 196));
        tablaPuntajes.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tablaPuntajes.setForeground(new java.awt.Color(255, 255, 255));
        tablaPuntajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Usuario", "Puntaje"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaPuntajes.setRowHeight(34);
        jScrollPane1.setViewportView(tablaPuntajes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 410, 330));

        regresarBtn.setBackground(new java.awt.Color(12, 241, 253));
        regresarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back-arrow_icon-icons.com_72866.png"))); // NOI18N
        regresarBtn.setFocusPainted(false);
        jPanel1.add(regresarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, 40, 50));

        salir.setBackground(new java.awt.Color(12, 241, 253));
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/letterx_83737.png"))); // NOI18N
        salir.setFocusPainted(false);
        salir.setFocusable(false);
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jPanel1.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 0, -1, 50));

        puntajeTxt.setBackground(new java.awt.Color(12, 156, 208));
        puntajeTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        puntajeTxt.setForeground(new java.awt.Color(255, 255, 255));
        puntajeTxt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        puntajeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntajeTxtActionPerformed(evt);
            }
        });
        jPanel1.add(puntajeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 110, 40));

        nicknameTxt.setBackground(new java.awt.Color(12, 156, 208));
        nicknameTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nicknameTxt.setForeground(new java.awt.Color(255, 255, 255));
        nicknameTxt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(nicknameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 110, 40));

        jLabel3.setBackground(new java.awt.Color(12, 156, 208));
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 760, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void puntajeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntajeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puntajeTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(estadisticasIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(estadisticasIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(estadisticasIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(estadisticasIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new estadisticasIndex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel BienvenidoLbl;
    public javax.swing.JLabel BienvenidoLbl1;
    public javax.swing.JLabel BienvenidoLbl2;
    public javax.swing.JLabel BienvenidoLbl3;
    public javax.swing.JLabel BienvenidoLbl4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField nicknameTxt;
    public javax.swing.JTextField puntajeTxt;
    public javax.swing.JButton regresarBtn;
    private javax.swing.JButton salir;
    public javax.swing.JTable tablaPuntajes;
    // End of variables declaration//GEN-END:variables
}
