/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.tiempo;


/**
 *
 * @author franc
 */
public class TiempoForm extends javax.swing.JFrame {

    /**
     * Creates new form TiempoRegistro
     */
    public TiempoForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regresarBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        registrarBtn = new javax.swing.JButton();
        eliminarBtn = new javax.swing.JButton();
        limpiarBtn = new javax.swing.JButton();
        modificarBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        eraTF = new javax.swing.JTextField();
        periodoTF = new javax.swing.JTextField();
        descubrimientoTF = new javax.swing.JTextField();
        epocaTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        regresarBtn.setBackground(new java.awt.Color(12, 241, 253));
        regresarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back-arrow_icon-icons.com_72866.png"))); // NOI18N
        getContentPane().add(regresarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, 40, -1));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Registro de periodo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 480, 60));

        jLabel5.setBackground(new java.awt.Color(87, 198, 196));
        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 103));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 190, 40));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 190, 10));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 190, 10));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 190, 10));

        registrarBtn.setBackground(new java.awt.Color(87, 198, 196));
        registrarBtn.setForeground(new java.awt.Color(255, 255, 255));
        registrarBtn.setText("Registrar");
        registrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarBtnActionPerformed(evt);
            }
        });
        getContentPane().add(registrarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 462, -1, -1));

        eliminarBtn.setBackground(new java.awt.Color(87, 198, 196));
        eliminarBtn.setForeground(new java.awt.Color(255, 255, 255));
        eliminarBtn.setText("Eliminar");
        getContentPane().add(eliminarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 462, -1, -1));

        limpiarBtn.setBackground(new java.awt.Color(87, 198, 196));
        limpiarBtn.setForeground(new java.awt.Color(255, 255, 255));
        limpiarBtn.setText("Limpiar");
        getContentPane().add(limpiarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 462, -1, -1));

        modificarBtn.setBackground(new java.awt.Color(87, 198, 196));
        modificarBtn.setForeground(new java.awt.Color(255, 255, 255));
        modificarBtn.setText("Modificar");
        getContentPane().add(modificarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 462, -1, -1));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Descubierto: ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Era: ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Periodo: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Epoca: ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        eraTF.setBackground(new java.awt.Color(12, 156, 208));
        eraTF.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        eraTF.setForeground(new java.awt.Color(255, 255, 255));
        eraTF.setBorder(null);
        eraTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eraTFActionPerformed(evt);
            }
        });
        getContentPane().add(eraTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 180, 25));

        periodoTF.setBackground(new java.awt.Color(12, 156, 208));
        periodoTF.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        periodoTF.setForeground(new java.awt.Color(255, 255, 255));
        periodoTF.setBorder(null);
        periodoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                periodoTFActionPerformed(evt);
            }
        });
        getContentPane().add(periodoTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 180, 25));

        descubrimientoTF.setBackground(new java.awt.Color(12, 156, 208));
        descubrimientoTF.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        descubrimientoTF.setForeground(new java.awt.Color(255, 255, 255));
        descubrimientoTF.setBorder(null);
        getContentPane().add(descubrimientoTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 180, 25));

        epocaTF.setBackground(new java.awt.Color(12, 156, 208));
        epocaTF.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        epocaTF.setForeground(new java.awt.Color(255, 255, 255));
        epocaTF.setBorder(null);
        getContentPane().add(epocaTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 180, 25));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/construction_project_plan_building_architect_design_develop-68_icon-icons.com_60246.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 160, -1, -1));

        jLabel6.setBackground(new java.awt.Color(12, 156, 208));
        jLabel6.setToolTipText("");
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1000, 400));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 190, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void periodoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_periodoTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_periodoTFActionPerformed

    private void registrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrarBtnActionPerformed

    private void eraTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eraTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eraTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TiempoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TiempoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TiempoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TiempoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TiempoForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField descubrimientoTF;
    public javax.swing.JButton eliminarBtn;
    public javax.swing.JTextField epocaTF;
    public javax.swing.JTextField eraTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    public javax.swing.JButton limpiarBtn;
    public javax.swing.JButton modificarBtn;
    public javax.swing.JTextField periodoTF;
    public javax.swing.JButton registrarBtn;
    public javax.swing.JButton regresarBtn;
    // End of variables declaration//GEN-END:variables
}
