/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dinobase;

/**
 *
 * @author franc
 */
public class login extends javax.swing.JFrame {


    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        BienvenidoLbl = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        userLbl = new javax.swing.JLabel();
        registrarseBtn = new javax.swing.JButton();
        loguearseBtn = new javax.swing.JButton();
        namePassLbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nicknameTF = new javax.swing.JTextField();
        nameNickNameLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        periodosLbl = new javax.swing.JLabel();
        namePeriodosLbl = new javax.swing.JLabel();
        paleontologosLbl = new javax.swing.JLabel();
        namePaleaLbl = new javax.swing.JLabel();
        paisesLbl = new javax.swing.JLabel();
        namePaisLbl = new javax.swing.JLabel();
        taxonomiasLbl = new javax.swing.JLabel();
        nameTaxLbl = new javax.swing.JLabel();
        climasLbl = new javax.swing.JLabel();
        nameClimasLbl = new javax.swing.JLabel();
        salir = new javax.swing.JButton();
        paisBtn = new javax.swing.JButton();
        tiempoBtn = new javax.swing.JButton();
        climaBtn = new javax.swing.JButton();
        paleanBtn = new javax.swing.JButton();
        taxBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 130, 40));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 130, 40));

        BienvenidoLbl.setBackground(new java.awt.Color(87, 198, 196));
        BienvenidoLbl.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        BienvenidoLbl.setForeground(new java.awt.Color(255, 255, 255));
        BienvenidoLbl.setText("Bienvenido");
        getContentPane().add(BienvenidoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        pass.setBackground(new java.awt.Color(87, 198, 196));
        pass.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        pass.setForeground(new java.awt.Color(255, 255, 255));
        pass.setBorder(null);
        getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 130, 20));

        userLbl.setBackground(new java.awt.Color(87, 198, 196));
        userLbl.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        userLbl.setForeground(new java.awt.Color(255, 255, 255));
        userLbl.setToolTipText("");
        getContentPane().add(userLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 160, -1));

        registrarseBtn.setBackground(new java.awt.Color(223, 122, 19));
        registrarseBtn.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        registrarseBtn.setForeground(new java.awt.Color(255, 255, 255));
        registrarseBtn.setText("Registrar");
        getContentPane().add(registrarseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, -1, -1));

        loguearseBtn.setBackground(new java.awt.Color(223, 122, 19));
        loguearseBtn.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        loguearseBtn.setForeground(new java.awt.Color(255, 255, 255));
        loguearseBtn.setText("Iniciar sesión");
        getContentPane().add(loguearseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        namePassLbl.setBackground(new java.awt.Color(87, 198, 196));
        namePassLbl.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        namePassLbl.setForeground(new java.awt.Color(255, 255, 255));
        namePassLbl.setText("Cotraseña:");
        getContentPane().add(namePassLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 140, 120));

        nicknameTF.setBackground(new java.awt.Color(87, 198, 196));
        nicknameTF.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        nicknameTF.setForeground(new java.awt.Color(255, 255, 255));
        nicknameTF.setBorder(null);
        getContentPane().add(nicknameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 130, 20));

        nameNickNameLbl.setBackground(new java.awt.Color(87, 198, 196));
        nameNickNameLbl.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        nameNickNameLbl.setForeground(new java.awt.Color(255, 255, 255));
        nameNickNameLbl.setText("NickName:");
        getContentPane().add(nameNickNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jLabel1.setBackground(new java.awt.Color(87, 198, 196));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 600));

        periodosLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1491254405-recenttimesearchreloadtime_82966.png"))); // NOI18N
        periodosLbl.setToolTipText("");
        getContentPane().add(periodosLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 120, 100, 100));

        namePeriodosLbl.setBackground(new java.awt.Color(255, 255, 255));
        namePeriodosLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        namePeriodosLbl.setForeground(new java.awt.Color(255, 255, 255));
        namePeriodosLbl.setText("Periodos");
        getContentPane().add(namePeriodosLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 220, -1, -1));

        paleontologosLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/paintbrush_79604.png"))); // NOI18N
        paleontologosLbl.setToolTipText("");
        getContentPane().add(paleontologosLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 360, 100, 100));

        namePaleaLbl.setBackground(new java.awt.Color(255, 255, 255));
        namePaleaLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        namePaleaLbl.setForeground(new java.awt.Color(255, 255, 255));
        namePaleaLbl.setText("Paleontologos");
        getContentPane().add(namePaleaLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 470, -1, -1));

        paisesLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/globe_106381.png"))); // NOI18N
        paisesLbl.setToolTipText("");
        getContentPane().add(paisesLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, 90, 100));

        namePaisLbl.setBackground(new java.awt.Color(255, 255, 255));
        namePaisLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        namePaisLbl.setForeground(new java.awt.Color(255, 255, 255));
        namePaisLbl.setText("Países");
        getContentPane().add(namePaisLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, -1, -1));

        taxonomiasLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dinosaur-bones_39225.png"))); // NOI18N
        taxonomiasLbl.setToolTipText("");
        getContentPane().add(taxonomiasLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 100, 100));

        nameTaxLbl.setBackground(new java.awt.Color(255, 255, 255));
        nameTaxLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nameTaxLbl.setForeground(new java.awt.Color(255, 255, 255));
        nameTaxLbl.setText("Taxonomias");
        getContentPane().add(nameTaxLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, -1, -1));

        climasLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/thermometer-temperature-control-tool-weather-interface-symbol_icon-icons.com_54635.png"))); // NOI18N
        climasLbl.setToolTipText("");
        getContentPane().add(climasLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, 100, 100));

        nameClimasLbl.setBackground(new java.awt.Color(255, 255, 255));
        nameClimasLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nameClimasLbl.setForeground(new java.awt.Color(255, 255, 255));
        nameClimasLbl.setText("Climas");
        getContentPane().add(nameClimasLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 470, -1, -1));

        salir.setBackground(new java.awt.Color(12, 156, 208));
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/x.png"))); // NOI18N
        salir.setBorderPainted(false);
        salir.setFocusPainted(false);
        salir.setFocusable(false);
        salir.setOpaque(false);
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, -1, -1));

        paisBtn.setBackground(new java.awt.Color(87, 198, 196));
        paisBtn.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        paisBtn.setText("Entrar");
        paisBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paisBtnActionPerformed(evt);
            }
        });
        getContentPane().add(paisBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, -1, -1));

        tiempoBtn.setBackground(new java.awt.Color(87, 198, 196));
        tiempoBtn.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        tiempoBtn.setText("Entrar");
        getContentPane().add(tiempoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 250, -1, -1));

        climaBtn.setBackground(new java.awt.Color(87, 198, 196));
        climaBtn.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        climaBtn.setText("Entrar");
        getContentPane().add(climaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 500, -1, -1));

        paleanBtn.setBackground(new java.awt.Color(87, 198, 196));
        paleanBtn.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        paleanBtn.setText("Entrar");
        getContentPane().add(paleanBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 500, -1, -1));

        taxBtn.setBackground(new java.awt.Color(87, 198, 196));
        taxBtn.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        taxBtn.setText("Entrar");
        getContentPane().add(taxBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, -1, -1));

        jLabel5.setBackground(new java.awt.Color(12, 156, 208));
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 830, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
         System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void paisBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paisBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paisBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel BienvenidoLbl;
    public javax.swing.JButton climaBtn;
    public javax.swing.JLabel climasLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JSeparator jSeparator3;
    public javax.swing.JSeparator jSeparator4;
    public javax.swing.JButton loguearseBtn;
    public javax.swing.JLabel nameClimasLbl;
    public javax.swing.JLabel nameNickNameLbl;
    public javax.swing.JLabel namePaisLbl;
    public javax.swing.JLabel namePaleaLbl;
    public javax.swing.JLabel namePassLbl;
    public javax.swing.JLabel namePeriodosLbl;
    public javax.swing.JLabel nameTaxLbl;
    public javax.swing.JTextField nicknameTF;
    public javax.swing.JButton paisBtn;
    public javax.swing.JLabel paisesLbl;
    public javax.swing.JButton paleanBtn;
    public javax.swing.JLabel paleontologosLbl;
    public javax.swing.JPasswordField pass;
    public javax.swing.JLabel periodosLbl;
    public javax.swing.JButton registrarseBtn;
    private javax.swing.JButton salir;
    public javax.swing.JButton taxBtn;
    public javax.swing.JLabel taxonomiasLbl;
    public javax.swing.JButton tiempoBtn;
    public javax.swing.JLabel userLbl;
    // End of variables declaration//GEN-END:variables
}
